version: '3.4'

services:
  webapitravisci:
    image: ${DOCKER_REGISTRY-}webapitravisci
    build:
      context: .
      dockerfile: WebApiTravisCI/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"
    networks:
      - travis-network
networks:
    travis-network:
        driver: bridge